name: Protect Main Branch

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  block-direct-push-to-main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        run: |
          echo "Direct pushes to the 'main' branch are not allowed. Please open a Pull Request from 'dev' to 'main' instead."
          exit 1

  allow-merge-from-dev:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from dev to main
        run: |
          if [ "${{ github.base_ref }}" != "main" ] || [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Pull Requests to 'main' are only allowed from the 'dev' branch."
            exit 1
          else
            echo "Pull Request from 'dev' to 'main' is allowed."
          fi
